const fs=require('fs');
let h=fs.readFileSync('index.html','utf8');
h=h.replace('window.onload = () => { ','window.onload = () => { console.log(\"[flow] window.onload\"); ');
h=h.replace('function initSystem() { ','function initSystem() { console.log(\"[flow] initSystem\"); ');
h=h.replace('async function fetchData() { ','async function fetchData() { console.log(\"[flow] fetchData\"); ');
h=h.replace('function openReport() { ','function openReport() { console.log(\"[flow] openReport\"); ');
h=h.replace('function openPending() { ','function openPending() { console.log(\"[flow] openPending\"); ');
h=h.replace('async function loadPending() { ','async function loadPending() { console.log(\"[flow] loadPending\"); ');
h=h.replace('function openHistory() { if(User','function openHistory() { console.log(\"[flow] openHistory\"); if(User');
h=h.replace('async function doHistorySearch() { ','async function doHistorySearch() { console.log(\"[flow] doHistorySearch\"); ');
h=h.replace('async function doLogin() { ','async function doLogin() { console.log(\"[flow] doLogin\"); ');
h=h.replace('function loginSuccess(n, a, u, token) { ','function loginSuccess(n, a, u, token) { console.log(\"[flow] loginSuccess\"); ');
h=h.replace('function setRestockMode(m) { UI.rsMode = m;','function setRestockMode(m) { console.log(\"[flow] setRestockMode\", m); UI.rsMode = m;');
h=h.replace('const d = await API.getInventory();','console.log(\"[flow] before getInventory\"); const d = await API.getInventory();');
h=h.replace('const res = await API.getPendingOrders();','console.log(\"[flow] before getPendingOrders\"); const res = await API.getPendingOrders();');
h=h.replace('const res = await API.getHistory(s, e);','console.log(\"[flow] before getHistory\"); const res = await API.getHistory(s, e);');
h=h.replace('const result = await API.verifyLogin(u, p);','console.log(\"[flow] before verifyLogin\"); const result = await API.verifyLogin(u, p);');
fs.writeFileSync('index.html',h);
console.log('done');
